mechion_test/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import include, path, re_path
from django.contrib.auth.views import LogoutView

from mechion_test import settings
from main import views as general_views
from web import views as web_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),

    # admin panel
    path('admin-panel/',include(('main.urls'),namespace='main')),
    path('app/',general_views.app,name='app'),

    path('product/',include(('product.urls'),namespace='product')),

    # web
    path('', web_views.home, name='home'),
    path('web/',include(('web.urls'),namespace='web')),
    path('login/', web_views.customer_join, name='login'),

    path('social-auth/', include('social_django.urls', namespace='social')),
    # path('logout/', LogoutView.as_view()),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

product/urls.py
from django.urls import path, re_path
from . import views

app_name = 'product'

urlpatterns = [
    path('brand/', views.brands, name='brand'),
    re_path(r'^create-brand/$', views.create_brand, name='create_brand'),
    re_path(r'^edit-brand/(?P<pk>.*)/$', views.edit_brand, name='edit_brand'),
    re_path(r'^delete-brand/(?P<pk>.*)/$', views.delete_brand, name='delete_brand'),

    path('product-list/', views.product_list, name='product_list'),
    re_path(r'^product-details/(?P<pk>.*)/$', views.product_details, name='product_details'),
    re_path(r'^create-product/$', views.create_product, name='create_product'),
    re_path(r'^edit-product/(?P<pk>.*)/$', views.edit_product, name='edit_product'),
    re_path(r'^delete-product/(?P<pk>.*)/$', views.delete_product, name='delete_product'),
]

web/urls.py
from django.urls import path, include, re_path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home_product/$', views.home_products, name='home_products'),
    re_path(r'^product/$', views.product_view, name='product_view'),

    re_path(r'^add-cart/(?P<pk>.*)/(?P<qty>.*)/$', views.add_cart, name='add_cart'),
    re_path(r'^remove-from-cart/(?P<pk>.*)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^increment-cart/(?P<pk>.*)/$', views.increment_cart, name='increment_cart'),
    re_path(r'^decrement-cart/(?P<pk>.*)/$', views.decrement_cart, name='decrement_cart'),
    re_path(r'^cart/$', views.cart, name='cart'),

    re_path(r'^add-address/$', views.add_address, name='add_address'),
    re_path(r'^create-order/$', views.create_order, name='create_order'),
    re_path(r'^payment-gateway/(?P<order_id>.*)/$', views.payment_gateway, name='payment_gateway'),

    re_path(r'^payment-response/(?P<order_id>.*)/$', views.payment_response, name="payment_response"),
    re_path(r'^payments/$',views.payments,name='payments'),
    re_path(r'^payment/(?P<pk>.*)/$',views.payment,name='payment'),
    re_path(r'^payment-success/(?P<order_id>.*)/$', views.payment_success, name="payment_success"),
    re_path(r'^payment-failed/$', views.payment_failed, name="payment_failed"),

    re_path(r'^invoice/(?P<order_id>.*)/$', views.invoice, name="invoice"),

    path('logout/', views.customer_logout, name='logout'),
]

product/models.py
# standerd
import uuid
import datetime
# django
from django.db import models
from django.core.validators import MinValueValidator
#third party
from decimal import Decimal
from versatileimagefield.fields import VersatileImageField
#local
from main.models import BaseModel

# Create your models here.

class Brand(BaseModel):
    name = models.CharField(max_length=200)

    class Meta:
        db_table = 'product_brand'
        verbose_name = ('Brand')
        verbose_name_plural = ('Brand')

    def __str__(self):
        return str(self.name)

class Product(BaseModel):
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    starp_color = models.CharField(max_length=200)
    highlights = models.CharField(max_length=200)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    stock = models.DecimalField(default=0, decimal_places=0, max_digits=15, validators=[MinValueValidator(Decimal('0'))])
    status = models.BooleanField(default=False)
    image = VersatileImageField('Image', upload_to="product/product_cover", blank=True, null=True)

    class Meta:
        db_table = 'product_product'
        verbose_name = ('Product')
        verbose_name_plural = ('Product')

    def __str__(self):
        return str(self.name)

product/forms.py
from django import forms
from django.forms.widgets import TextInput,Textarea,Select,DateInput,CheckboxInput,FileInput

from . models import *

# Create your views here.
class BrandsForm(forms.ModelForm):

    class Meta:
        model = Brand
        fields = ['name']

        widgets = {
            'name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Brand Name'}),
        }

class ProductForm(forms.ModelForm):

    status = forms.BooleanField(required=False)

    class Meta:
        model = Product
        fields = ['brand','name','starp_color','highlights','price','stock','status','image']

        widgets = {
            'brand': Select(attrs={'class': 'select2 form-control mb-3 custom-select','placeholder' : 'Enter Brand'}),
            'name': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Name'}),
            'starp_color': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Strap Color'}),
            'highlights': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Highlights'}),
            'price': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Price'}),
            'stock': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Stock'}),
            'status': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Status'}),
            'image': FileInput(attrs={'class': 'form-control dropify'}),
        }

    def clean_image(self):

        image_file = self.cleaned_data.get('image')
        if not (image_file.name.endswith(".jpg") or image_file.name.endswith(".png") or image_file.name.endswith(".jpeg")):
            raise forms.ValidationError("Only .jpg or .png files are accepted")
        return image_file

product/views.py
#standerd
import json
import datetime
#django
from django.http import HttpResponse
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
#thirdparty
#local
from product.forms import *
from main.functions import generate_form_errors, get_auto_id, paginate
from product.models import *
from main.decorators import role_required


# #*******************************CRUD Brands***************************************


@login_required
@role_required(['superadmin'])
def brands(request):
    """
    brands listings
    :param request:
    :return: brands list view
    """
    instances = Brand.objects.filter(is_deleted=False).order_by("-id")

    filter_data = {}
    query = request.GET.get("q")

    if query:

        instances = instances.filter(
            Q(auto_id__icontains=query) |
            Q(name__icontains=query)
        )
        title = "Brands - %s" % query
        filter_data['q'] = query


    context = {
        'instances': instances,
        'page_name' : 'Brands',
        'page_title' : 'Brands',
        'filter_data' :filter_data,
    }

    return render(request, 'admin_panel/product/brand.html', context)


@login_required
@role_required(['superadmin'])
def create_brand(request):
    """
    create operation of brand
    :param request:
    :param pk:
    :return:
    """
    if request.method == 'POST':
        # if instance go to edit
        form = BrandsForm(request.POST)

        if form.is_valid():
            data = form.save(commit=False)
            data.auto_id = get_auto_id(Brand)
            data.creator = request.user
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully Created",
                "message": "brand created successfully.",
                'redirect': 'true',
                "redirect_url": reverse('product:brand')
            }

        else:
            message =generate_form_errors(form , formset=False)
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message,
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:

        form = BrandsForm()

        context = {
            'form': form,
            'page_name' : 'Create brand',
            'page_title' : 'Create brand',
            'url' : reverse('product:create_brand'),
        }

        return render(request, 'admin_panel/create/create.html',context)


@login_required
@role_required(['superadmin'])
def edit_brand(request,pk):
    """
    edit operation of brand
    :param request:
    :param pk:
    :return:
    """
    instance = get_object_or_404(Brand, pk=pk)

    message = ''
    if request.method == 'POST':
        form = BrandsForm(request.POST,instance=instance)

        if form.is_valid():

            #update brand
            data = form.save(commit=False)
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully Created",
                "message": "brand Update successfully.",
                'redirect': 'true',
                "redirect_url": reverse('product:brand')
            }

        else:
            message = generate_form_errors(form ,formset=False)


            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:

        form = BrandsForm(instance=instance)

        context = {
            'form': form,
            'page_name' : 'Create brand',
            'page_title' : 'Create brand',
            'is_need_select2' : True,
            'url' : reverse('product:brand'),
        }

        return render(request, 'admin_panel/create/create.html',context)


@login_required
@role_required(['superadmin'])
def delete_brand(request, pk):
    """
    brand deletion, it only mark as is deleted field to true
    :param request:
    :param pk:
    :return:
    """
    Brand.objects.filter(pk=pk).update(is_deleted=True)

    response_data = {
        "status": "true",
        "title": "Successfully Deleted",
        "message": "Product Successfully Deleted.",
        "redirect": "true",
        "redirect_url": reverse('product:brand')
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


#*******************************CRUD Product***************************************


@login_required
@role_required(['superadmin'])
def product_list(request):
    """
    product listings
    :param request:
    :return: product list view
    """
    instances = Product.objects.filter(is_deleted=False).order_by("-date_added")

    filter_data = {}
    query = request.GET.get("q")

    if query:

        instances = instances.filter(
            Q(auto_id__icontains=query) |
            Q(name__icontains=query) |
            Q(brand__name__icontains=query)
        )
        title = "Products - %s" % query
        filter_data['q'] = query


    context = {
        'instances': instances,
        'page_name' : 'Products',
        'page_title' : 'Products',
        'filter_data' : filter_data
    }

    return render(request, 'admin_panel/product/product_list.html', context)


@login_required
@role_required(['superadmin'])
def product_details(request,pk):
    """
    product single view using product pk
    :param request:
    :pk
    :return: product list view
    """
    instance = Product.objects.get(pk=pk, is_deleted=False)

    context = {
        'instance': instance,
        'page_name' : 'Product Details',
        'page_title' : 'Product Details',
        'is_need_light_box' : True,
    }

    return render(request, 'admin_panel/product/product_details.html', context)


@login_required
@role_required(['superadmin'])
def create_product(request):
    """
    create operation of product
    :param request:
    :return:
    """

    message = ''
    if request.method == 'POST':
        form = ProductForm(request.POST,files=request.FILES)

        if form.is_valid() :

            #create product
            data = form.save(commit=False)
            data.auto_id = get_auto_id(Product)
            data.creator = request.user
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully Created",
                "message": "Product created successfully.",
                'redirect': 'true',
                "redirect_url": reverse('product:product_list')
            }

        else:
            message = generate_form_errors(form, formset=False)

            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message,
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:
        form = ProductForm()

        context = {
            'form': form,
            'page_name' : 'Create Product',
            'page_title' : 'Create Product',
            'is_need_select2' : True,
            'url' : reverse('product:create_product'),
        }

        return render(request, 'admin_panel/create/create.html',context)


@login_required
@role_required(['superadmin'])
def edit_product(request,pk):
    """
    edit operation of product
    :param request:
    :param pk:
    :return:
    """
    product_instance = get_object_or_404(Product, pk=pk)

    message = ''

    if request.method == 'POST':
        form = ProductForm(request.POST,files=request.FILES,instance=product_instance)

        if form.is_valid():
            #create product
            data = form.save(commit=False)
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully Updated",
                "message": "Product Successfully Updated.",
                "redirect": "true",
                "redirect_url": reverse('product:product_list')
            }

        else:
            message = generate_form_errors(form,formset=False)

            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:

        form = ProductForm(instance=product_instance)

        context = {
            'form': form,
            'message': message,
            'page_name' : 'edit product'

        }

        return render(request, 'admin_panel/create/create.html', context)


@login_required
@role_required(['superadmin'])
def delete_product(request, pk):
    """
    product deletion, it only mark as is deleted field to true
    :param request:
    :param pk:
    :return:
    """
    Product.objects.filter(pk=pk).update(is_deleted=True)

    response_data = {
        "status": "true",
        "title": "Successfully Deleted",
        "message": "Product Successfully Deleted.",
        "redirect": "true",
        "redirect_url": reverse('product:product_list')
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/admin_panel/product/brand.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Brand List</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Brands</a></li>
                                    <li class="breadcrumb-item active">List</li>
                                </ol>
                            </div><!--end col-->
                            <div class="col-auto col-sm-2 float-right ml-auto">
                                <form method="get" action="{% url 'product:brand' %}">
                                    <li class="list-inline-item">
                                        <div class="input-group">

                                            <input name="q" type="text" placeholder="Search" value="{{ filter_data.q }}"
                                                class="form-control" />
                                            <span class="input-group-append">
                                                <button type="button" class="btn btn-soft-primary btn-sm"><i
                                                        class="fas fa-search"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                </form>
                            </div>
                            <div class="col-auto align-self-center">
                                <a class="btn btn-primary btn-sm text-white px-4 d-inline-block"  href="{% url 'product:create_brand' %}" ><i class="mdi mdi-plus mr-2"></i>Brand</a>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                            <tr>
                                <th style="width:2%">SL.No</th>
                                <th style="width:85%">Name</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% load el_pagination_tags %}
                            {% paginate 20 instances %}
                            {%for brand in instances%}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{brand.name}}</td>

                                <td>
                                    <a href="{% url 'product:product_details' pk=product.pk %}" class="mr-2"><i class="las la-eye text-info font-18"></i></a>
                                    <a href="{% url 'product:edit_product' pk=product.pk %}" class="mr-2"><i class="las la-pen text-info font-18"></i></a>
                                    <a data-id="{{ product.pk }}" class="action-button remove redirect" href="{% url 'product:delete_product' pk=product.pk %}" data-text="{{ confirm_delete_message }}" data-title="Are you sure?"><i class="las la-trash-alt text-danger font-18"></i></a>
                                </td>
                            </tr>
                            {%endfor%}
                            {% comment %} {% show_pages %} {% endcomment %}

                            </tbody>
                        </table>

                        {% get_pages %}
                        <div class="clearfix"></div>
                        <div class="row pagi my-3">
                            <div class="col-sm-6 col-xs-6 text-left my-pagina">{% show_pages %}</div>
                            <div class="col-sm-6 col-xs-6 text-right tot my-pagination align-items-center">
                                <div class="m-t-10">
                                    Showing {{title}}
                                    <span class="current_page_index">{{ pages.current_start_index }}</span> - <span
                                        class="current_end_status">{{ pages.current_end_index }}</span> of <span
                                        class="total_count">{{ pages.total_count }}</span>
                                </div>
                            </div>
                        </div>

                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->

        </div><!-- container -->
    </div>
    <!-- end page content -->
{% endblock content %}

templates/admin_panel/product/product_list.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">Product List</h4>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Dashboard</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0);">Products</a></li>
                                    <li class="breadcrumb-item active">List</li>
                                </ol>
                            </div><!--end col-->
                            <div class="col-auto col-sm-2 float-right ml-auto">
                                <form method="get" action="{% url 'product:product_list' %}">
                                    <li class="list-inline-item">
                                        <div class="input-group">

                                            <input name="q" type="text" placeholder="Search" value="{{ filter_data.q }}"
                                                class="form-control" />
                                            <span class="input-group-append">
                                                <button type="button" class="btn btn-soft-primary btn-sm"><i
                                                        class="fas fa-search"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                </form>
                            </div>
                            <div class="col-auto align-self-center">
                                <a class="btn btn-primary btn-sm text-white px-4 d-inline-block"  href="{% url 'product:create_product' %}" ><i class="mdi mdi-plus mr-2"></i>Product</a>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                            <tr>
                                <th>SL.No</th>
                                <th>Name</th>
                                <th>Brand</th>
                                <th>Strap Color</th>
                                <th>Highlights</th>
                                <th>Price</th>
                                <th>Stock</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% load el_pagination_tags %}
                            {% paginate 20 instances %}
                            {%for product in instances%}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>
                                    {% if product.image %}
                                    <img src="{{product.image.url}}" alt="" height="40" width="15%">
                                    {% endif %}
                                    <p class="d-inline-block align-middle mb-0">
                                        <a href="#" class="d-inline-block align-middle mb-0 product-name">{{product.name}}</a>
                                    </p>
                                </td>
                                <td>{{product.brand.name}}</td>
                                <td>{{product.starp_color}}</td>
                                <td>{{product.highlights}}</td>
                                <td>{{product.price}}</td>
                                <td>{{product.stock}}</td>
                                <td>
                                    {% if product.status %}
                                    <span style="color:green">Available</span>
                                    {% else %}
                                    <span style="color:red">Not Available</span>
                                    {% endif %}
                                </td>

                                <td>
                                    <a href="{% url 'product:product_details' pk=product.pk %}" class="mr-2"><i class="las la-eye text-info font-18"></i></a>
                                    <a href="{% url 'product:edit_product' pk=product.pk %}" class="mr-2"><i class="las la-pen text-info font-18"></i></a>
                                    <a data-id="{{ product.pk }}" class="action-button remove redirect" href="{% url 'product:delete_product' pk=product.pk %}" data-text="{{ confirm_delete_message }}" data-title="Are you sure?"><i class="las la-trash-alt text-danger font-18"></i></a>
                                </td>
                            </tr>
                            {%endfor%}
                            {% comment %} {% show_pages %} {% endcomment %}

                            </tbody>
                        </table>

                        {% get_pages %}
                        <div class="clearfix"></div>
                        <div class="row pagi my-3">
                            <div class="col-sm-6 col-xs-6 text-left my-pagina">{% show_pages %}</div>
                            <div class="col-sm-6 col-xs-6 text-right tot my-pagination align-items-center">
                                <div class="m-t-10">
                                    Showing {{title}}
                                    <span class="current_page_index">{{ pages.current_start_index }}</span> - <span
                                        class="current_end_status">{{ pages.current_end_index }}</span> of <span
                                        class="total_count">{{ pages.total_count }}</span>
                                </div>
                            </div>
                        </div>

                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->

        </div><!-- container -->
    </div>
    <!-- end page content -->
{% endblock content %}