mechion_test/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import include, path, re_path
from django.contrib.auth.views import LogoutView

from mechion_test import settings
from main import views as general_views
from web import views as web_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),

    # admin panel
    path('admin-panel/',include(('main.urls'),namespace='main')),
    path('app/',general_views.app,name='app'),

    path('product/',include(('product.urls'),namespace='product')),

    # web
    path('', web_views.home, name='home'),
    path('web/',include(('web.urls'),namespace='web')),
    path('login/', web_views.customer_join, name='login'),

    path('social-auth/', include('social_django.urls', namespace='social')),
    # path('logout/', LogoutView.as_view()),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

product/urls.py
from django.urls import path, re_path
from . import views

app_name = 'product'

urlpatterns = [
    path('brand/', views.brands, name='brand'),
    re_path(r'^create-brand/$', views.create_brand, name='create_brand'),
    re_path(r'^edit-brand/(?P<pk>.*)/$', views.edit_brand, name='edit_brand'),
    re_path(r'^delete-brand/(?P<pk>.*)/$', views.delete_brand, name='delete_brand'),

    path('product-list/', views.product_list, name='product_list'),
    re_path(r'^product-details/(?P<pk>.*)/$', views.product_details, name='product_details'),
    re_path(r'^create-product/$', views.create_product, name='create_product'),
    re_path(r'^edit-product/(?P<pk>.*)/$', views.edit_product, name='edit_product'),
    re_path(r'^delete-product/(?P<pk>.*)/$', views.delete_product, name='delete_product'),
]

web/urls.py
from django.urls import path, include, re_path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home_product/$', views.home_products, name='home_products'),
    re_path(r'^product/$', views.product_view, name='product_view'),

    re_path(r'^add-cart/(?P<pk>.*)/(?P<qty>.*)/$', views.add_cart, name='add_cart'),
    re_path(r'^remove-from-cart/(?P<pk>.*)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^increment-cart/(?P<pk>.*)/$', views.increment_cart, name='increment_cart'),
    re_path(r'^decrement-cart/(?P<pk>.*)/$', views.decrement_cart, name='decrement_cart'),
    re_path(r'^cart/$', views.cart, name='cart'),

    re_path(r'^add-address/$', views.add_address, name='add_address'),
    re_path(r'^create-order/$', views.create_order, name='create_order'),
    re_path(r'^payment-gateway/(?P<order_id>.*)/$', views.payment_gateway, name='payment_gateway'),

    re_path(r'^payment-response/(?P<order_id>.*)/$', views.payment_response, name="payment_response"),
    re_path(r'^payments/$',views.payments,name='payments'),
    re_path(r'^payment/(?P<pk>.*)/$',views.payment,name='payment'),
    re_path(r'^payment-success/(?P<order_id>.*)/$', views.payment_success, name="payment_success"),
    re_path(r'^payment-failed/$', views.payment_failed, name="payment_failed"),

    re_path(r'^invoice/(?P<order_id>.*)/$', views.invoice, name="invoice"),

    path('logout/', views.customer_logout, name='logout'),
]

product/models.py
# standerd
import uuid
import datetime
# django
from django.db import models
from django.core.validators import MinValueValidator
#third party
from decimal import Decimal
from versatileimagefield.fields import VersatileImageField
#local
from main.models import BaseModel

# Create your models here.

class Brand(BaseModel):
    name = models.CharField(max_length=200)

    class Meta:
        db_table = 'product_brand'
        verbose_name = ('Brand')
        verbose_name_plural = ('Brand')

    def __str__(self):
        return str(self.name)

class Product(BaseModel):
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    starp_color = models.CharField(max_length=200)
    highlights = models.CharField(max_length=200)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    stock = models.DecimalField(default=0, decimal_places=0, max_digits=15, validators=[MinValueValidator(Decimal('0'))])
    status = models.BooleanField(default=False)
    image = VersatileImageField('Image', upload_to="product/product_cover", blank=True, null=True)

    class Meta:
        db_table = 'product_product'
        verbose_name = ('Product')
        verbose_name_plural = ('Product')

    def __str__(self):
        return str(self.name)

product/forms.py
from django import forms
from django.forms.widgets import TextInput,Textarea,Select,DateInput,CheckboxInput,FileInput

from . models import *

# Create your views here.
class BrandsForm(forms.ModelForm):

    class Meta:
        model = Brand
        fields = ['name']

        widgets = {
            'name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Enter Brand Name'}),
        }

class ProductForm(forms.ModelForm):

    status = forms.BooleanField(required=False)

    class Meta:
        model = Product
        fields = ['brand','name','starp_color','highlights','price','stock','status','image']

        widgets = {
            'brand': Select(attrs={'class': 'select2 form-control mb-3 custom-select','placeholder' : 'Enter Brand'}),
            'name': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Name'}),
            'starp_color': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Strap Color'}),
            'highlights': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Highlights'}),
            'price': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Price'}),
            'stock': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Stock'}),
            'status': TextInput(attrs={'class': 'required form-control h-20','placeholder' : 'Enter Status'}),
            'image': FileInput(attrs={'class': 'form-control dropify'}),
        }

    def clean_image(self):

        image_file = self.cleaned_data.get('image')
        if not (image_file.name.endswith(".jpg") or image_file.name.endswith(".png") or image_file.name.endswith(".jpeg")):
            raise forms.ValidationError("Only .jpg or .png files are accepted")
        return image_file

product/views.py
#standerd
import json
import datetime
#django
from django.http import HttpResponse
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
#thirdparty
#local
from product.forms import *
from main.functions import generate_form_errors, get_auto_id, paginate
from product.models import *
from main.decorators import role_required


# #*******************************CRUD Brands***************************************


@login_required
@role_required(['superadmin'])
def brands(request):
    """
    brands listings
    :param request:
    :return: brands list view
    """
    instances = Brand.objects.filter(is_deleted=False).order_by("-id")

    filter_data = {}
    query = request.GET.get("q")

    if query:

        instances = instances.filter(
            Q(auto_id__icontains=query) |
            Q(name__icontains=query)
        )
        title = "Brands - %s" % query
        filter_data['q'] = query


    context = {
        'instances': instances,
        'page_name' : 'Brands',
        'page_title' : 'Brands',
        'filter_data' :filter_data,
    }

    return render(request, 'admin_panel/product/brand.html', context)


@login_required
@role_required(['superadmin'])
def create_brand(request):
    """
    create operation of brand
    :param request:
    :param pk:
    :return:
    """
    if request.method == 'POST':
        # if instance go to edit
        form = BrandsForm(request.POST)

        if form.is_valid():
            data = form.save(commit=False)
            data.auto_id = get_auto_id(Brand)
            data.creator = request.user
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully Created",
                "message": "brand created successfully.",
                'redirect': 'true',
                "redirect_url": reverse('product:brand')
            }

        else:
            message =generate_form_errors(form , formset=False)
            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message,
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:

        form = BrandsForm()

        context = {
            'form': form,
            'page_name' : 'Create brand',
            'page_title' : 'Create brand',
            'url' : reverse('product:create_brand'),
        }

        return render(request, 'admin_panel/create/create.html',context)


@login_required
@role_required(['superadmin'])
def edit_brand(request,pk):
    """
    edit operation of brand
    :param request:
    :param pk:
    :return:
    """
    instance = get_object_or_404(Brand, pk=pk)

    message = ''
    if request.method == 'POST':
        form = BrandsForm(request.POST,instance=instance)

        if form.is_valid():

            #update brand
            data = form.save(commit=False)
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully Created",
                "message": "brand Update successfully.",
                'redirect': 'true',
                "redirect_url": reverse('product:brand')
            }

        else:
            message = generate_form_errors(form ,formset=False)


            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:

        form = BrandsForm(instance=instance)

        context = {
            'form': form,
            'page_name' : 'Create brand',
            'page_title' : 'Create brand',
            'is_need_select2' : True,
            'url' : reverse('product:brand'),
        }

        return render(request, 'admin_panel/create/create.html',context)


@login_required
@role_required(['superadmin'])
def delete_brand(request, pk):
    """
    brand deletion, it only mark as is deleted field to true
    :param request:
    :param pk:
    :return:
    """
    Brand.objects.filter(pk=pk).update(is_deleted=True)

    response_data = {
        "status": "true",
        "title": "Successfully Deleted",
        "message": "Product Successfully Deleted.",
        "redirect": "true",
        "redirect_url": reverse('product:brand')
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


#*******************************CRUD Product***************************************


@login_required
@role_required(['superadmin'])
def product_list(request):
    """
    product listings
    :param request:
    :return: product list view
    """
    instances = Product.objects.filter(is_deleted=False).order_by("-date_added")

    filter_data = {}
    query = request.GET.get("q")

    if query:

        instances = instances.filter(
            Q(auto_id__icontains=query) |
            Q(name__icontains=query) |
            Q(brand__name__icontains=query)
        )
        title = "Products - %s" % query
        filter_data['q'] = query


    context = {
        'instances': instances,
        'page_name' : 'Products',
        'page_title' : 'Products',
        'filter_data' : filter_data
    }

    return render(request, 'admin_panel/product/product_list.html', context)


@login_required
@role_required(['superadmin'])
def product_details(request,pk):
    """
    product single view using product pk
    :param request:
    :pk
    :return: product list view
    """
    instance = Product.objects.get(pk=pk, is_deleted=False)

    context = {
        'instance': instance,
        'page_name' : 'Product Details',
        'page_title' : 'Product Details',
        'is_need_light_box' : True,
    }

    return render(request, 'admin_panel/product/product_details.html', context)


@login_required
@role_required(['superadmin'])
def create_product(request):
    """
    create operation of product
    :param request:
    :return:
    """

    message = ''
    if request.method == 'POST':
        form = ProductForm(request.POST,files=request.FILES)

        if form.is_valid() :

            #create product
            data = form.save(commit=False)
            data.auto_id = get_auto_id(Product)
            data.creator = request.user
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully Created",
                "message": "Product created successfully.",
                'redirect': 'true',
                "redirect_url": reverse('product:product_list')
            }

        else:
            message = generate_form_errors(form, formset=False)

            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message,
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:
        form = ProductForm()

        context = {
            'form': form,
            'page_name' : 'Create Product',
            'page_title' : 'Create Product',
            'is_need_select2' : True,
            'url' : reverse('product:create_product'),
        }

        return render(request, 'admin_panel/create/create.html',context)


@login_required
@role_required(['superadmin'])
def edit_product(request,pk):
    """
    edit operation of product
    :param request:
    :param pk:
    :return:
    """
    product_instance = get_object_or_404(Product, pk=pk)

    message = ''

    if request.method == 'POST':
        form = ProductForm(request.POST,files=request.FILES,instance=product_instance)

        if form.is_valid():
            #create product
            data = form.save(commit=False)
            data.date_updated = datetime.datetime.today()
            data.updater = request.user
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully Updated",
                "message": "Product Successfully Updated.",
                "redirect": "true",
                "redirect_url": reverse('product:product_list')
            }

        else:
            message = generate_form_errors(form,formset=False)

            response_data = {
                "status": "false",
                "title": "Failed",
                "message": message
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:

        form = ProductForm(instance=product_instance)

        context = {
            'form': form,
            'message': message,
            'page_name' : 'edit product'

        }

        return render(request, 'admin_panel/create/create.html', context)


@login_required
@role_required(['superadmin'])
def delete_product(request, pk):
    """
    product deletion, it only mark as is deleted field to true
    :param request:
    :param pk:
    :return:
    """
    Product.objects.filter(pk=pk).update(is_deleted=True)

    response_data = {
        "status": "true",
        "title": "Successfully Deleted",
        "message": "Product Successfully Deleted.",
        "redirect": "true",
        "redirect_url": reverse('product:product_list')
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Mechion Test | {{page_name}}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}

        <!-- styles -->
        <link href="{% static 'web/style.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'web/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

        <link href="{% static 'admin_panel/assets/sweet/sweetalert2.css' %}" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
              <img src="{% static 'web/images/logo.png' %}" alt="logo" style="width:40px;">
            </a>

            <!-- Links -->
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'web:home'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'web:cart'%}">Cart</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'web:logout'%}">Logout</a>
              </li>
            </ul>
        </nav>
        {% block content %}

        {% endblock  %}
        <script src="{% static 'admin_panel/assets/js/jquery.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

        <script src="{% static 'admin_panel/assets/sweet/actions.js' %}"></script>
        <script src="{% static 'admin_panel/assets/sweet/sweetalert2.js' %}"></script>
        {% block static %}

        {% endblock %}
    </body>
</html>

templates/web/cart.html
{% extends 'web/base.html' %}
{% load static %}
{% load web_templatetag %}


{% block content %}

<section class="h-100" style="background-color: #eee;">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">

        <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
        </div>
        {% for instance in instances %}
        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <img
                  src="{{instance.product.image.url}}"
                  class="img-fluid rounded-3" alt="{{instance.product.name}}">
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">{{instance.product.name}}</p>
                <p><span class="text-muted">Brand: </span>{{instance.product.brand.name}}</p>
                <p><span class="text-muted">Color: </span>{{instance.product.starp_color}}</p>
              </div>
              {% get_have_stock instance.product.pk as have_stock %}
              {% if have_stock %}
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <a href="{% url 'web:decrement_cart' pk=instance.pk %}" class="btn btn-link px-2"><i class="fa fa-minus"></i></a>
                <input id="form1 number{{instance.pk}}" min="0" name="quantity" value="{{instance.qty}}" type="number" class="form-control form-control-sm" disabled/>
                <a href="{% url 'web:increment_cart' pk=instance.pk %}" class="btn btn-link px-2"><i class="fa fa-plus"></i></a>
              </div>
              {% else %}
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <p style="color:red">Out of Stock</p>
              </div>
              {% endif %}



              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">₹{{instance.unit_price}}</h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <a data-id="{{ instance.pk }}" class="action-button remove redirect text-danger" href="{% url 'web:remove_from_cart' pk=instance.pk %}" data-text="{{ confirm_delete_message }}" data-title="Are you sure?"><i class="fa fa-trash fa-lg"></i></a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        <div class="card">
          <div class="card-body">
            <a href="{% url 'web:add_address' %}"><button type="button" class="btn btn-warning btn-block btn-lg">Proceed to Pay</button></a>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}

{% block content %}

<section class="section-products">
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col-md-8 col-lg-6">
                <div class="header">
                    <h3>Featured Product</h3>
                    <h2>Popular Products</h2>
                </div>
            </div>
        </div>
        <div class="row" id="products">
            <!-- Single Product -->

        </div>
    </div>
</section>

{% endblock content %}
{% block static %}
{% load static %}
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        url =  "/web/home_product/";
        $.ajax({
			type: "GET",
			url: url,
			dataType: "json",
			data: {},

			success: function (data) {
				if (data["status"] == "true") {
                    console.log(data['data'])
                    products = data['data']

                    for(var i=0; i<products.length; i++){
                        product = products[i]
                        $('#products').append(
                            `<div class="col-md-6 col-lg-4 col-xl-3" onclick="window.location.href='{% url 'web:product_view' %}?pk=${product["id"]}'">
                                <div id="product-1" class="single-product">
                                    <div class="part-1" style="background: url(${product["image"]}) no-repeat center;)">
                                        <ul>
                                            <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="part-2">
                                        <h3 class="product-title">${product["name"]}</h3>
                                        <h4 class="product-price">Rs: ${product["price"]}</h4>
                                    </div>
                                </div>
                            </div>`
                        )
                    }
				}
			},

			error: function (data) {
				//    console.log("errrorrrr")
			},
		});
    });
</script>
{% endblock %}

templates/web/product.html
{% extends 'web/base.html' %}
{% load static %}
{% load web_templatetag %}

{% block content %}

<div class="super_container">
    <header class="header" style="display: none;">
        <div class="header_main">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-12 order-lg-2 order-3 text-lg-left text-right">
                        <div class="header_search">
                            <div class="header_search_content">
                                <div class="header_search_form_container">
                                    <form action="#" class="header_search_form clearfix">
                                        <div class="custom_dropdown">
                                            <div class="custom_dropdown_list"> <span class="custom_dropdown_placeholder clc">All Categories</span> <i class="fa fa-chevron-down"></i>
                                                <ul class="custom_list clc">
                                                    <li><a class="clc" href="#">All Categories</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="single_product">
        <div class="container-fluid" style=" background-color: #fff; padding: 11px;">
            <div class="row">
                <div class="col-lg-2 order-lg-1 order-2">

                </div>
                <div class="col-lg-4 order-lg-2 order-1">
                    <div class="image_selected"><img src="{{instance.image.url}}" alt=""></div>
                </div>
                <div class="col-lg-6 order-3">
                    <div class="product_description">
                        <nav>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Products</a></li>
                                <li class="breadcrumb-item active">Accessories</li>
                            </ol>
                        </nav>
                        <div class="product_name">{{instance.name}}</div>
                        <div> <span class="product_price">₹ {{instance.price}}</span></div>
                        <hr class="singleline">
                        <div>
                            <span class="product_info">Strap Color: {{instance.starp_color}}</span><br>
                            <span class="product_info">Highlights: {{instance.highlights}}</span><br>
                            <span class="product_info" style="color:red">

                                {% if not instance.status %}
                                Out of Stock
                                {% endif %}

                            </span><br>
                        </div>

                        {% get_have_cart instance.pk request.user as have_cart %}
                        <div class="row">

                            <div class="col-xs-6" style="margin-left: 13px;">
                                {% get_have_stock instance.pk as have_stock %}

                                {% if have_stock %}
                                <div class="product_quantity"> <span>QTY: </span> <input id="number" type="text" pattern="[0-9]*" value="{% if have_cart.status %}{{have_cart.qty}}{% else %}1{% endif %}" id="counting">
                                    <div class="quantity_buttons">
                                        <div id="increase" class="quantity_inc quantity_control" onclick="increaseValue('{{instance.stock}}')" value="Increase Value"><i class="fa fa-chevron-up"></i></div>
                                        <div id="decrease" class="quantity_dec quantity_control" onclick="decreaseValue()" value="Decrease Value"><i class="fa fa-chevron-down"></i></div>
                                    </div>
                                </div>
                                {% else %}
                                <p style="color:red">Out of Stock</p>
                                {% endif %}
                            </div>

                            <div class="col-xs-6">
                            {% if have_cart.status %}
                            <a href="{% url 'web:cart' %}"><button type="button" class="btn btn-success shop-button">Goto Cart</button></a>
                            {% else %}
                            <button type="submit" id="submit" class="btn btn-primary shop-button btn btn-soft-primary btn-sm waves-effect waves-light" onclick="getQtyValue()">Add to Cart</button>
                            {% endif %}
                                <div class="product_fav"><i class="fa fa-heart"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script>
    function increaseValue(stock) {
        var value = parseInt(document.getElementById('number').value, 10);
        if (document.getElementById('number').value!=stock) {
            value = isNaN(value) ? 0 : value;
            value++;
            document.getElementById('number').value = value;
        }
      }

      function decreaseValue() {
        var value = parseInt(document.getElementById('number').value, 10);
        value = isNaN(value) ? 0 : value;
        value < 1 ? value = 1 : '';
        value--;
        document.getElementById('number').value = value;
      }

      function getQtyValue(){
        val = $("#number").val();
        url = "/web/add-cart/{{instance.pk}}/"+val+"/";

        $.ajax({
			type: "GET",
			url: url,
			dataType: "json",
			data: {},

			success: function (data) {
                console.log(data['redirect_url']+"ulllskjvnjfdnrvjr j======")
				if (data["status"] == "true") {

                    swal({
                        type: 'success',
                        title: data['title'],
                        text: data['message'],
                      }, function () {
                        window.location.href = data['redirect_url']+"?pk={{instance.pk}}";
                    });
				}
			},

			error: function (data) {
				//    console.log("errrorrrr")
			},
		});
    }
</script>

{% endblock content %}

{% block static %}
    {% load static %}



{%endblock%}