mechion_test/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import include, path, re_path
from django.contrib.auth.views import LogoutView

from mechion_test import settings
from main import views as general_views
from web import views as web_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),

    # admin panel
    path('admin-panel/',include(('main.urls'),namespace='main')),
    path('app/',general_views.app,name='app'),

    path('product/',include(('product.urls'),namespace='product')),

    # web
    path('', web_views.home, name='home'),
    path('web/',include(('web.urls'),namespace='web')),
    path('login/', web_views.customer_join, name='login'),

    path('social-auth/', include('social_django.urls', namespace='social')),
    # path('logout/', LogoutView.as_view()),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

web/urls.py
from django.urls import path, include, re_path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home_product/$', views.home_products, name='home_products'),
    re_path(r'^product/$', views.product_view, name='product_view'),

    re_path(r'^add-cart/(?P<pk>.*)/(?P<qty>.*)/$', views.add_cart, name='add_cart'),
    re_path(r'^remove-from-cart/(?P<pk>.*)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^increment-cart/(?P<pk>.*)/$', views.increment_cart, name='increment_cart'),
    re_path(r'^decrement-cart/(?P<pk>.*)/$', views.decrement_cart, name='decrement_cart'),
    re_path(r'^cart/$', views.cart, name='cart'),

    re_path(r'^add-address/$', views.add_address, name='add_address'),
    re_path(r'^create-order/$', views.create_order, name='create_order'),
    re_path(r'^payment-gateway/(?P<order_id>.*)/$', views.payment_gateway, name='payment_gateway'),

    re_path(r'^payment-response/(?P<order_id>.*)/$', views.payment_response, name="payment_response"),
    re_path(r'^payments/$',views.payments,name='payments'),
    re_path(r'^payment/(?P<pk>.*)/$',views.payment,name='payment'),
    re_path(r'^payment-success/(?P<order_id>.*)/$', views.payment_success, name="payment_success"),
    re_path(r'^payment-failed/$', views.payment_failed, name="payment_failed"),

    re_path(r'^invoice/(?P<order_id>.*)/$', views.invoice, name="invoice"),

    path('logout/', views.customer_logout, name='logout'),
]

payment/models.py
#django
from django.db import models
from django.core.validators import MinValueValidator
#third party
from decimal import Decimal
#local
from main.models import BaseModel


# Create your models here.
class Payment(BaseModel):
    order_id = models.CharField(max_length=200)
    amount = models.DecimalField(default=0, decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    currency = models.CharField(max_length=200,null=True,blank=True)
    language = models.CharField(max_length=200,null=True,blank=True)
    payment_type = models.CharField(max_length=200,null=True,blank=True)
    payment_mode = models.CharField(max_length=200,null=True,blank=True)
    card_name = models.CharField(max_length=200,null=True,blank=True)
    order_status = models.CharField(max_length=200,null=True,blank=True)
    transaction_id = models.CharField(max_length=200,null=True,blank=True)
    transaction_signature = models.CharField(max_length=200,null=True,blank=True)
    bank_ref_no = models.CharField(max_length=200,null=True,blank=True)
    bank_id = models.CharField(max_length=200,null=True,blank=True)
    payuid = models.CharField(max_length=200,null=True,blank=True)
    mihpayuid = models.CharField(max_length=200,null=True,blank=True)
    payment_order_id = models.CharField(max_length=200,null=True,blank=True)
    description = models.TextField(max_length=200,null=True,blank=True)
    payment_channel = models.CharField(max_length=200,null=True,blank=True)
    payment_datetime = models.CharField(max_length=200,null=True,blank=True)
    response_code = models.CharField(max_length=200,null=True,blank=True)
    response_message = models.CharField(max_length=200,null=True,blank=True)
    error_desc = models.CharField(max_length=200,null=True,blank=True)
    cardmasked = models.CharField(max_length=200,null=True,blank=True)
    failure_message = models.TextField(max_length=200,null=True,blank=True)
    status_message = models.TextField(max_length=200,null=True,blank=True)

    class Meta:
        db_table = 'payment'
        verbose_name = ('Payment')
        verbose_name_plural = ('Payment')

    def __str__(self):
        return str(self.order_id)

payment/views.py
from django.shortcuts import render

# Create your views here.

templates/web/payments/failure.html
<html>
<body>
<div style="display:none">
   	<input type="hidden" name="csrfmiddlewaretoken" value="{% csrf_token %}">
</div>
<h2>{{response_message}}</h2>
</body>
</html>

templates/web/payments/invalid.html
{% extends "ecommerce/web/base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
    <div>
        <div class="row wrapper border-bottom white-bg p-h-xs">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-lg-5">
                        <h3>Invalid Transaction</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
            	<div class="ibox p-md">
					<div class="m-b-none p-md">Invalid Transaction. Reason : {{invalid_reason}}.</div>
				</div>
            </div><!-- div.col-lg-12 -->

        </div><!-- div.row -->
    </div> <!-- div.wrapper -->
{% endblock %}


{% block static %}
    {% load static %}
{% endblock %}

templates/web/payments/order-successfull.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

<section class="h-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-10 col-xl-8">
          <div class="card" style="border-radius: 10px;">
            <div class="card-header px-4 py-5">
              <h5 class="text-muted mb-0">Thanks for your Order</h5>
            </div>
            <div class="card-body p-4">
              <div class="d-flex justify-content-between align-items-center mb-4">
                <p class="lead fw-normal mb-0" style="color: #a8729a;">Receipt</p>
                <p class="small text-muted mb-0">Order ID : {{order.order_id}}</p>
              </div>

              {% for item in order_items %}

              <div class="card shadow-0 border mb-4">
                <div class="card-body">
                  <div class="row">
                    <div class="col-md-2">
                      <img src="{{item.product.image.url}}"
                        class="img-fluid" alt="Phone">
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0">{{item.product.name}}</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Color: {{item.product.starp_color}}</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Highlights: {{item.product.highlights}}</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Qty: {{item.qty}}</p>
                    </div>
                    <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">₹ {{item.subtotal}}</p>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}

              <div class="d-flex justify-content-between pt-2">
                <p class="fw-bold mb-0">Order Details</p>
                <p class="text-muted mb-0"><span class="fw-bold me-4">Total</span> ₹{{order.total_amount}}</p>
              </div>

              <div class="d-flex justify-content-between pt-2">
                <p class="text-muted mb-0">Invoice Number : 788152</p>
              </div>

              <div class="d-flex justify-content-between">
                <p class="text-muted mb-0">Invoice Date : {{order.time}}</p>
                <p class="text-muted mb-0"><a href="{% url 'web:invoice' order_id=order.order_id %}">Print invoice</a></p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/web/payments/payment.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load users_template_tags %}
{% load tz %}
{% block content %}
    <section id="content">
      <div class="container">
            <div class="row wrapper white-bg p-h-xs">
                <div class="col-lg-12">
                    <div class="col-lg-7">
                        <h3 style="color: #fff;">{{title}}</h3>
                    </div>
                </div>
            </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Basic Details </h5>
                    </div>
                    <div class="ibox-content">
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Time</h4>
                                <p>{{instance.date_added|timezone:user_time_zone}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Amount</h4>
                                <p>{{instance.amount|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Currency</h4>
                                <p>{{instance.currency|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Order Id</h4>
                                <p style="color:#a30707f7">{{instance.order_id|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Order Status</h4>
                                <p style="color:#a30707f7">{{instance.order_status|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Transaction ID</h4>
                                <p style="color:#a30707f7">{{instance.transaction_id|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Payment ID.</h4>
                                <p style="color:#a30707f7">{{instance.payment_order_id|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Failure Message</h4>
                                <p>{{instance.failure_message|default:"-"}}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div><!-- div.col-lg-6 -->

            <div class="col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Basic Details </h5>
                    </div>
                    <div class="ibox-content">
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Language</h4>
                                <p>{{instance.language|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Order Status</h4>
                                <p>{{instance.order_status|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Payment Mode</h4>
                                <p>{{instance.payment_mode|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Payment Type</h4>
                                <p>{{instance.payment_type|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Card Name</h4>
                                <p>{{instance.card_name|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Status Code</h4>
                                <p>{{instance.status_code|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Status Message</h4>
                                <p>{{instance.status_message|default:"-"}}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div><!-- div.col-lg-6 -->

            <div class="col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Delivery Info </h5>
                    </div>
                    <div class="ibox-content">
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Delivery Name</h4>
                                <p>{{instance.delivery_name|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Delivery Address</h4>
                                <p>{{instance.delivery_address|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Delivery City</h4>
                                <p>{{instance.delivery_city|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Delivery zip</h4>
                                <p>{{instance.delivery_zip|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Delivery Country</h4>
                                <p>{{instance.delivery_country|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Delivery Phone</h4>
                                <p>{{instance.delivery_tel|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Delivery Email</h4>
                                <p>{{instance.delivery_email|default:"-"}}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div><!-- div.col-lg-6 -->

            <div class="col-lg-6">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Billing Info </h5>
                    </div>
                    <div class="ibox-content">
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Billing Nam</h4>
                                <p>{{instance.delivery_name|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Billing Address</h4>
                                <p>{{instance.billing_name|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Billing City</h4>
                                <p>{{instance.billing_city|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Billing zip</h4>
                                <p>{{instance.billing_zip|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Billing Country</h4>
                                <p>{{instance.billing_country|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Billing Phone</h4>
                                <p>{{instance.billing_tel|default:"-"}}</p>
                            </div>
                        </div>
                        <div class="m-b-md">
                            <div class="media-body">
                                <h4>Billing Email</h4>
                                <p>{{instance.billing_email|default:"-"}}</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div><!-- div.col-lg-6 -->
        </div> <!-- div.row -->
    </div><!-- div.wrapper -->
</section>
{% endblock %}


{% block static %}
    {% load static %}
{% endblock %}

templates/web/payments/payment_request.html
<html>
  <head onload="submitPayuForm()">
  {% csrf_token %}
    <script>
      var hash = "{{ hash }}";
      function formAutoSubmit () {
        if(hash =='') {
              return;
            }
        var payform = document.getElementById("tnpForm");
        payform.submit();
      }
      window.onload = formAutoSubmit;
    </script>
     {% load static %} 
  </head>
  <body>
      <!-- <h2 class="main">TraknPay Form</h2> -->
      <div class="image">
          <img src="{% static 'web/images/animation.gif' %}" alt="Loading.." />
      </div>
        
      <form action={{ action }} method="post" id="tnpForm">
        <input type="hidden" name="api_key" value="{{ API_KEY }}" />
        <input type="hidden" name="hash" value="{{ hash }}"/>
      	<label>amount</label>
        <input type="text" name="amount" value="{{ posted.amount}}" required><br><br>

      	<label>Email</label>
        <input type="text" name="email" value="{{ posted.email }}" required><br><br>

        <label>Name</label>
        <input type="text" name="name" value="{{ posted.name }}" required><br><br>

        <label>Phone</label>
        <input type="text" name="phone" value="{{ posted.phone}}" required><br><br>

        <label>Adress 1</label>
      	<input type="text" name="address_line_1" value="{{ posted.address_line_1}}" required><br><br>

      	<label>Address 2</label>
      	<input type="text" name="address_line_2" value="{{ posted.address_line_2}}"><br><br>

      	<label>Order Id</label>
      	<input type="text" name="order_id" value="{{ posted.order_id }}" required><br><br>

      	<label>Currency</label>
      	<input type="text" name="currency" value="{{posted.currency}}" required><br><br>

      	<label>Description</label>
      	<input type="text" name="description" value="{{posted.description}}" required><br><br>

      	<label>City</label>
      	<input type="text" name="city" value="{{ posted.city }}" required><br><br>

      	<label>State</label>
      	<input type="text" name="state" value="{{ posted.state }}"><br><br>

      	<label>Zip Code</label>
      	<input type="text" name="zip_code" value="{{ posted.zip_code}}" required><br><br>

      	<label>Counrty</label>
      	<input type="text" name="country"  value="{{posted.country}}" required><br><br>

      	<label>return_url</label>
      	<input type="text" name="return_url" value="{{ posted.return_url |default:'http://127.0.0.1:8000/paymets/payment_response/'}}" required><br><br>

      	<label>mode</label>
      	<input type="text" name="mode" value="{{ posted.mode|default:'TEST' }}" required><br><br>

      	<label>udf1</label>
        <input type="text" name="udf1" ><br><br>

        <label>udf2</label>
        <input type="text" name="udf2" ><br><br>

        <label>udf3</label>
        <input type="text" name="udf3" ><br><br>

        <label>udf4</label>
        <input type="text" name="udf4" ><br><br>

        <label>udf5</label>
        <input type="text" name="udf5" ><br><br>
        
        <div class="buttons">
          <div class="right">
            <input type="submit" value="Submit" class="button" />
          </div>
        </div>
      </form>
  </body>
</html>
<meta name="viewport" content="width=device-width" initial-scale="1.0" />
<style type="text/css">
    form {
      visibility: hidden
    }
    h2.main {
      padding: 130px 0;
      text-align: center;
      font-size: 30px;
    }
    div.image {
      width: 350px;
      margin: 0 auto;
      position: absolute;
      top: 177px;
      left: 0;
      right: 0;
    }
    div.image img {
      display: block;
      width: 100%;
    }
  @media all and (max-width: 1285px){
      h2.main {
        font-size: 40px;
      }
  }
  @media all and (max-width: 768px){
      h2.main {
        padding-top : 105px;
      }
  }
  @media all and (max-width: 480px){
      h2.main {
        font-size: 35px;
      }
      div.image {
        top: 155px;
      }
  }
  
</style>

templates/web/payments/payment_success.html
{% extends 'web/webbase.html' %}
{% load i18n %}

{% load static %}
{% load tz %}
{% block content %}
	<section id="page">
		<div class="content">
			<h3>Your Transaction Successful</h3>
		</div>
	</section>
{% endblock %}

{% block static %}
    {% load static %}
    <style type="text/css">
    	body {
    		margin :0;
    	}
	    #page{
			background: #fff;
			width: 100%;
			background-size: cover;
			padding: 150px 0 90px;
		}
		#page div.content{
			text-align: center;
			position: relative;
		    top: 35%;
		    bottom: 0;
		    left: 0;
		    right: 0;
		    margin: auto;
		    color: #fff;
		}
		#page div.content h3{
			font-size: 35px;
			color: #fff;
			margin-bottom: 0;
			color: #000;
		}
		#page div.content p{
			font-size: 20px;
		    margin-top: 6px;
		    margin-bottom: 30px;
		    color: #000;
		}
		#page div.content a{

		}
		#page div.content a.button1{
			color: #fff;
			padding: 10px 35px;
			border-radius: 50px;
			-webkit-border-radius: 50px;
			display: inline-block;
			font-size: 20px;
			margin-top: 20px;
			text-align: center;
			border: 2px solid #fff;
		}

    </style>

{% endblock %}	