mechion_test/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import include, path, re_path
from django.contrib.auth.views import LogoutView

from mechion_test import settings
from main import views as general_views
from web import views as web_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),

    # admin panel
    path('admin-panel/',include(('main.urls'),namespace='main')),
    path('app/',general_views.app,name='app'),

    path('product/',include(('product.urls'),namespace='product')),

    # web
    path('', web_views.home, name='home'),
    path('web/',include(('web.urls'),namespace='web')),
    path('login/', web_views.customer_join, name='login'),

    path('social-auth/', include('social_django.urls', namespace='social')),
    # path('logout/', LogoutView.as_view()),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

product/urls.py
from django.urls import path, re_path
from . import views

app_name = 'product'

urlpatterns = [
    path('brand/', views.brands, name='brand'),
    re_path(r'^create-brand/$', views.create_brand, name='create_brand'),
    re_path(r'^edit-brand/(?P<pk>.*)/$', views.edit_brand, name='edit_brand'),
    re_path(r'^delete-brand/(?P<pk>.*)/$', views.delete_brand, name='delete_brand'),

    path('product-list/', views.product_list, name='product_list'),
    re_path(r'^product-details/(?P<pk>.*)/$', views.product_details, name='product_details'),
    re_path(r'^create-product/$', views.create_product, name='create_product'),
    re_path(r'^edit-product/(?P<pk>.*)/$', views.edit_product, name='edit_product'),
    re_path(r'^delete-product/(?P<pk>.*)/$', views.delete_product, name='delete_product'),
]

web/urls.py
from django.urls import path, include, re_path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home_product/$', views.home_products, name='home_products'),
    re_path(r'^product/$', views.product_view, name='product_view'),

    re_path(r'^add-cart/(?P<pk>.*)/(?P<qty>.*)/$', views.add_cart, name='add_cart'),
    re_path(r'^remove-from-cart/(?P<pk>.*)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^increment-cart/(?P<pk>.*)/$', views.increment_cart, name='increment_cart'),
    re_path(r'^decrement-cart/(?P<pk>.*)/$', views.decrement_cart, name='decrement_cart'),
    re_path(r'^cart/$', views.cart, name='cart'),

    re_path(r'^add-address/$', views.add_address, name='add_address'),
    re_path(r'^create-order/$', views.create_order, name='create_order'),
    re_path(r'^payment-gateway/(?P<order_id>.*)/$', views.payment_gateway, name='payment_gateway'),

    re_path(r'^payment-response/(?P<order_id>.*)/$', views.payment_response, name="payment_response"),
    re_path(r'^payments/$',views.payments,name='payments'),
    re_path(r'^payment/(?P<pk>.*)/$',views.payment,name='payment'),
    re_path(r'^payment-success/(?P<order_id>.*)/$', views.payment_success, name="payment_success"),
    re_path(r'^payment-failed/$', views.payment_failed, name="payment_failed"),

    re_path(r'^invoice/(?P<order_id>.*)/$', views.invoice, name="invoice"),

    path('logout/', views.customer_logout, name='logout'),
]

templates/admin_panel/includes/sidebar/super_admin_side_bar.html
{% load static %}
<div class="left-sidenav">
    <!-- LOGO -->
    <div class="brand">
        <a href="{% url 'app' %}" class="logo">
            <span>
                <img src="{% static '' %}" alt="logo-small" class="logo-sm" style="height: 50px;">
            </span>
        </a>
    </div>
    <!--end logo-->
    <div class="menu-content h-100" data-simplebar>
        <ul class="metismenu left-sidenav-menu">
            <li class="menu-label mt-0">Main</li>
            <li>
                <a href="#"> <i data-feather="home" class="align-self-center menu-icon"></i><span>Dashboard</span><span class="menu-arrow"><i class="mdi mdi-chevron-down"></i></span></a>
            </li>
            
            <li>
                <a href="javascript: void(0);"> <i data-feather="layers" class="align-self-center menu-icon"></i><span>Products</span><span class="menu-arrow"><i class="mdi mdi-chevron-right"></i></span></a>
                <ul class="nav-second-level" aria-expanded="false">
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'product:brand' %}"><i class="ti-control-record"></i>Brands</a>
                        <a class="nav-link" href="{% url 'product:create_brand' %}"><i class="ti-plus"></i></a>
                    </li>
                    <li class="nav-item d-flex justify-content-between">
                        <a class="nav-link" href="{% url 'product:product_list' %}"><i class="ti-control-record"></i>Products</a>
                        <a class="nav-link" href="{% url 'product:create_product' %}"><i class="ti-plus"></i></a>
                    </li>

                </ul>
            </li>
        </ul>
    </div>
</div>